version: '3.4'
services:
    localstack:
        image: localstack/localstack:0.14.3.1
        container_name: tf_localstack
        ports:
            - 4566:4566
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

networks:
    default:
        name: localstack
        